#------------------------
# Postgres configuration
#------------------------

postgres.host: localhost
postgres.port: 5434
postgres.user: postgres
postgres.password: mysecretpassword
postgres.database: postgres
postgres.sslmode: disable
# The amount of time before the connection times out
postgres.connection.timeout: 5
# Duration to wait before trying to connect again
postgres.connection.retrysleep: 1s
postgres.connection.maxidle: -1
postgres.connection.maxopen: -1
# Timeout for a transaction in minutes
postgres.transaction.timeout: 5m

#------------------------
# HTTP configuration
#------------------------

http.address: 0.0.0.0:8087

#------------------------
# Misc.
#------------------------

# Enable development related features, e.g. token generation endpoint
developer.mode.enabled: false
log.level: info
