kind: Template
apiVersion: v1
metadata:
  name: cluster
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      service: cluster
    name: cluster
  spec:
    replicas: ${{REPLICAS}}
    selector:
      service: cluster
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          service: cluster
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          env:
          - name: CLUSTER_POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: cluster
                key: db.host
          - name: CLUSTER_POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: cluster
                key: db.port
          - name: CLUSTER_POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: cluster
                key: db.user
          - name: CLUSTER_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cluster
                key: db.password
          - name: CLUSTER_SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: cluster
                key: sentry.dsn
          - name: CLUSTER_POSTGRES_SSLMODE
            valueFrom:
              configMapKeyRef:
                name: cluster
                key: postgres.sslmode
          - name: CLUSTER_POSTGRES_CONNECTION_MAXIDLE
            valueFrom:
              configMapKeyRef:
                name: cluster
                key: postgres.connection.maxidle
          - name: CLUSTER_POSTGRES_CONNECTION_MAXOPEN
            valueFrom:
              configMapKeyRef:
                name: cluster
                key: postgres.connection.maxopen
          - name: CLUSTER_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: cluster
                key: environment
          imagePullPolicy: Always
          name: cluster
          ports:
          - containerPort: 8087
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/status
              port: 8087
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/status
              port: 8087
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 0.1m
              memory: 10Mi
            limits:
              cpu: 400m
              memory: 1.5Gi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /etc/fabric8/
            name: cluster-configs
            readOnly: true
        volumes:
        - name: cluster-configs
          secret:
            secretName: cluster-config-files
            items:
            - key: oso.clusters
              path: oso-clusters.conf
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status:
    details:
      causes:
      - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    name: cluster
    labels:
      service: cluster
  spec:
    ports:
      - name: "8087"
        protocol: TCP
        port: 80
        targetPort: 8087
    selector:
      service: cluster
    type: ClusterIP
    sessionAffinity: null
parameters:
- name: IMAGE
  value: quay.io/openshiftio/rhel-fabric8-services-fabric8-cluster
- name: IMAGE_TAG
  value: latest
- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: '1'
